plugins:
  - jekyll-redirect-from

safe: false

highlighter: rouge

remote_theme: b2a3e8/jekyll-theme-console

style: dark

title: 'a polyglot adventure | Advent of Code Solutions'
description: 'a polyglot adventure | Advent of Code Solutions'
baseurl: '/adventofcode-solutions'
url: 'https://booniepepper.github.io'

header_pages:
  - so-dang-cool.md
  - index.md
  - resources.md

footer: "Come now, let us reason together."

